### ISSUE TITLE
defaultAdmins 一项如何设置

### ISSUE THREAD

**Issue by wh7** [danmaqua/danmaqua-telegrambot#3]
比如我的用户ID是123456，config.js中是
`defaultAdmins: [123456],`
设置机器人时依然显示无相应权限。用不同的账号试了一下，还是不可以。

**Comment by WordlessEcho** [comment]
可以尝试一下删除数据库然后重新运行

**Comment by wh7** [comment]
> 可以尝试一下删除数据库然后重新运行

删除数据库后该问题解决。

现在又有新问题。用 `/subscribe [房间id] [频道id]`时 bot提示“你指定的目标不允许机器人发送消息，请检查机器人是否被禁言和是否未加入聊天。”尽管我已经将bot添加到对应频道的admin中。

**Comment by fython** [comment]
> > 可以尝试一下删除数据库然后重新运行
> 
> 删除数据库后该问题解决。
> 
> 现在又有新问题。用 `/subscribe [房间id] [频道id]`时 bot提示“你指定的目标不允许机器人发送消息，请检查机器人是否被禁言和是否未加入聊天。”尽管我已经将bot添加到对应频道的admin中。

@wh7 传入给机器人的频道与群组 ID 需要是带 `-100` 开头的格式，仅当传入用户 ID 不需要。

例如 [@dmq_minatoaqua](https://t.me/dmq_minatoaqua) 在一些工具中查看到的 ID 是 `1334623747` ，实际上要让机器人接口识别需要使用 `-1001334623747` 。

**Comment by wh7** [comment]
@fython 感谢，成功添加。

**Comment by WordlessEcho** [comment]
> > 可以尝试一下删除数据库然后重新运行
> 
> 删除数据库后该问题解决。
> 
> 现在又有新问题。用 `/subscribe [房间id] [频道id]`时 bot提示“你指定的目标不允许机器人发送消息，请检查机器人是否被禁言和是否未加入聊天。”尽管我已经将bot添加到对应频道的admin中。

第二个参数（也就是“频道ID”）也可以直接使用username，例如`/subscribe 21304638 @dmq_KaguraNana`

**Comment by wh7** [comment]
@WordlessEcho 感谢！
